### ISSUE TITLE
Link broken on blog post Wordpress Bye Bye

### ISSUE THREAD

**Issue by tusharjoshi** [tariquesani/tariquesani.net#1]
The link for What I chose ultimately and why is written in a tag in the file  

> tariquesani.net/content/blog/bye-bye-wordpress/contents.lr

`<a href="/refreshed/2016/8/lektor-lessons-learned/" >separate post</a>`

this tag is broken as there is no post named lektor-lessons-learned

**Comment by tariquesani** [comment]
Thanks, fixed via https://github.com/tariquesani/tariquesani.net/commit/58452b1cd8dd77b4c41de8abd0d647c987b4c5d3

**Comment by tusharjoshi** [comment]
Welcome, hope you know that text "fixes #1" anywhere in your commit message, automatically fixes the issue, on github for you.
